generic-service:
  nameOverride: hmpps-esupervision-api
  productId: "HMPPS9999" # productId for the product that this belongs too, i.e. DPS001, see README.md for details
  serviceAccountName: hmpps-esupervision-api

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-esupervision-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-esupervision-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-esupervision-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

    # postgres connection settings
    hmpps-esupervision-rds-settings:
      POSTGRES_ENDPOINT: "rds_instance_endpoint"
      POSTGRES_USERNAME: "database_username"
      POSTGRES_PASSWORD: "database_password"
      POSTGRES_DATABASE: "database_name"

    # s3 settings
    hmpps-esupervision-data-s3-bucket:
      S3_DATA_BUCKET_NAME: "bucket_name"

    hmpps-esupervision-rekog-aws:
      REKOG_AWS_REGION: 'region'
      REKOG_S3_DATA_BUCKET: 'bucket_name'
      REKOG_AWS_ACCESS_KEY_ID: "aws_access_key_id"
      REKOG_AWS_SECRET_ACCESS_KEY: "aws_secret_access_key"

    # gov.uk notify settings
    hmpps-esupervision-notify-api-key:
      NOTIFY_API_KEY: "API_KEY"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-esupervision-api
