-- liquibase formatted sql

-- changeset denis:11_create_v2_tables-1 splitStatements:false
CREATE TYPE offender_status_v2 AS ENUM ('INITIAL', 'VERIFIED', 'INACTIVE');

CREATE TABLE IF NOT EXISTS "offender_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" UUID NOT NULL CONSTRAINT "uk_offender_v2_uuid" UNIQUE,
    "crn" VARCHAR(7) NOT NULL CONSTRAINT "uk_offender_v2_crn" UNIQUE,
    "practitioner_id" VARCHAR(255) NOT NULL,
    "status" offender_status_v2 NOT NULL,
    "first_checkin" DATE NOT NULL,
    "checkin_interval" INTERVAL SECOND(6) NOT NULL,
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT "offender_v2_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "idx_offender_v2_uuid" ON "offender_v2" ("uuid");
CREATE INDEX "idx_offender_v2_crn" ON "offender_v2" ("crn");
CREATE INDEX "idx_offender_v2_status" ON "offender_v2" ("status");
CREATE INDEX "idx_offender_v2_practitioner" ON "offender_v2" ("practitioner_id");

-- changeset denis:11_create_v2_tables-2 splitStatements:false
CREATE TABLE IF NOT EXISTS "offender_setup_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" UUID NOT NULL CONSTRAINT "uk_offender_setup_v2_uuid" UNIQUE,
    "offender_id" BIGINT NOT NULL,
    "practitioner_id" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "started_at" TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT "offender_setup_v2_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk_setup_v2_offender" FOREIGN KEY ("offender_id") REFERENCES "offender_v2" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX "idx_setup_v2_uuid" ON "offender_setup_v2" ("uuid");
CREATE INDEX "idx_setup_v2_offender" ON "offender_setup_v2" ("offender_id");
CREATE INDEX "idx_setup_v2_practitioner" ON "offender_setup_v2" ("practitioner_id");

-- changeset denis:11_create_v2_tables-3 splitStatements:false
CREATE TYPE offender_checkin_status_v2 as ENUM ('CREATED', 'SUBMITTED', 'REVIEWED', 'EXPIRED', 'CANCELLED');
CREATE TYPE verify_id_manual_result_v2 as ENUM ('MATCH', 'NO_MATCH');
CREATE TYPE verify_id_auto_result_v2 as ENUM ('MATCH', 'NO_MATCH');

CREATE TABLE IF NOT EXISTS "offender_checkin_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" UUID NOT NULL CONSTRAINT "uk_offender_checkin_v2_uuid" UNIQUE,
    "offender_id" BIGINT NOT NULL,
    "status" offender_checkin_status_v2 NOT NULL,
    "due_date" DATE NOT NULL,
    "survey_response" JSONB,
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "submitted_at" TIMESTAMP(6) WITH TIME ZONE,
    "review_started_at" TIMESTAMP(6) WITH TIME ZONE,
    "review_started_by" VARCHAR(255),
    "reviewed_at" TIMESTAMP(6) WITH TIME ZONE,
    "reviewed_by" VARCHAR(255),
    "checkin_started_at" TIMESTAMP(6) WITH TIME ZONE,
    "auto_id_check" verify_id_auto_result_v2,
    "manual_id_check" verify_id_manual_result_v2,
    CONSTRAINT "offender_checkin_v2_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk_checkin_v2_offender" FOREIGN KEY ("offender_id") REFERENCES "offender_v2" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX "idx_checkin_v2_uuid" ON "offender_checkin_v2" ("uuid");
CREATE INDEX "idx_checkin_v2_offender" ON "offender_checkin_v2" ("offender_id");
CREATE INDEX "idx_checkin_v2_status" ON "offender_checkin_v2" ("status");
CREATE INDEX "idx_checkin_v2_due_date" ON "offender_checkin_v2" ("due_date");
CREATE INDEX "idx_checkin_v2_created_by" ON "offender_checkin_v2" ("created_by");
CREATE INDEX "idx_checkin_v2_created_at" ON "offender_checkin_v2" ("created_at");
CREATE INDEX "idx_checkin_v2_submitted_at" ON "offender_checkin_v2" ("submitted_at") WHERE "submitted_at" IS NOT NULL;
CREATE INDEX "idx_checkin_v2_reviewed_at" ON "offender_checkin_v2" ("reviewed_at") WHERE "reviewed_at" IS NOT NULL;
CREATE INDEX "idx_checkin_v2_status_due_date" ON "offender_checkin_v2" ("status", "due_date");
CREATE INDEX "idx_checkin_v2_offender_status_due" ON "offender_checkin_v2" ("offender_id", "status", "due_date");

-- changeset denis:11_create_v2_tables-4 splitStatements:false
CREATE TABLE IF NOT EXISTS "notification_config_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "event_type" VARCHAR(100) NOT NULL CONSTRAINT "uk_notification_config_v2_event_type" UNIQUE,
    "offender_sms_enabled" BOOLEAN NOT NULL DEFAULT true,
    "offender_email_enabled" BOOLEAN NOT NULL DEFAULT true,
    "offender_sms_template_id" VARCHAR(255),
    "offender_email_template_id" VARCHAR(255),
    "practitioner_sms_enabled" BOOLEAN NOT NULL DEFAULT false,
    "practitioner_email_enabled" BOOLEAN NOT NULL DEFAULT false,
    "practitioner_sms_template_id" VARCHAR(255),
    "practitioner_email_template_id" VARCHAR(255),
    "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "updated_by" VARCHAR(255) NOT NULL,
    CONSTRAINT "notification_config_v2_pkey" PRIMARY KEY ("id")
);

-- changeset denis:11_create_v2_tables-6 splitStatements:false
CREATE TYPE generic_notification_recipient_v2 as ENUM ('OFFENDER', 'PRACTITIONER');
CREATE TYPE generic_notification_channel_v2 as ENUM ('SMS', 'EMAIL');

CREATE TABLE IF NOT EXISTS "generic_notification_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "notification_id" UUID NOT NULL CONSTRAINT "uk_generic_notification_v2_notification_id" UNIQUE,
    "event_type" VARCHAR(100) NOT NULL,
    "recipient_type" generic_notification_recipient_v2 NULL,
    "channel" generic_notification_channel_v2 NOT NULL,
    "offender_id" BIGINT,
    "practitioner_id" VARCHAR(255),
    "status" VARCHAR(50),
    "reference" VARCHAR(255) NOT NULL,
    "template_id" VARCHAR(255),
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "sent_at" TIMESTAMP(6) WITH TIME ZONE,
    "updated_at" TIMESTAMP(6) WITH TIME ZONE,
    "error_message" VARCHAR(1000),
    CONSTRAINT "generic_notification_v2_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk_notification_v2_offender" FOREIGN KEY ("offender_id") REFERENCES "offender_v2" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX "idx_notification_v2_offender" ON "generic_notification_v2" ("offender_id");
CREATE INDEX "idx_notification_v2_event_type" ON "generic_notification_v2" ("event_type");
CREATE INDEX "idx_notification_v2_reference" ON "generic_notification_v2" ("reference");
CREATE INDEX "idx_notification_v2_status" ON "generic_notification_v2" ("status");
CREATE INDEX "idx_notification_v2_created_at" ON "generic_notification_v2" ("created_at");
CREATE INDEX "idx_notification_v2_practitioner" ON "generic_notification_v2" ("practitioner_id") WHERE "practitioner_id" IS NOT NULL;
CREATE INDEX "idx_notification_v2_status_created" ON "generic_notification_v2" ("status", "created_at");

-- changeset denis:11_create_v2_tables-7 splitStatements:false
-- Create V2 job log table (independent from V1)
CREATE TYPE job_type_v2 as ENUM ('V2_CHECKIN_CREATION', 'V2_CHECKIN_EXPIRY');

CREATE TABLE IF NOT EXISTS "job_log_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "ended_at" TIMESTAMP(6) WITH TIME ZONE,
    "job_type" job_type_v2 NOT NULL,
    CONSTRAINT "job_log_v2_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "idx_job_log_v2_created_at" ON "job_log_v2" ("created_at");
CREATE INDEX "idx_job_log_v2_job_type" ON "job_log_v2" ("job_type");
CREATE INDEX "idx_job_log_v2_type_created" ON "job_log_v2" ("job_type", "created_at" DESC);

-- changeset denis:11_create_v2_tables-8 splitStatements:false
-- Add default notification configuration for V2 events
INSERT INTO "notification_config_v2" (
    "event_type",
    "offender_sms_enabled", "offender_email_enabled",
    "practitioner_sms_enabled", "practitioner_email_enabled",
    "offender_sms_template_id", "offender_email_template_id",
    "practitioner_sms_template_id", "practitioner_email_template_id",
    "updated_at", "updated_by"
) VALUES
-- Setup Completed
('SETUP_COMPLETED',
 true, true,  -- Offender: SMS + Email
 false, false, -- Practitioner: Disabled
 '35274201-ecef-493b-b4e1-86e60d071142', -- Offender SMS template
 '7e63c01c-05df-4b2c-a77c-57d2412793a1', -- Offender Email template
 null, null,  -- Practitioner: N/A
 NOW(), 'SYSTEM'),

-- Checkin Created
('CHECKIN_CREATED',
 true, true,  -- Offender: SMS + Email (invite)
 false, true, -- Practitioner: Email enabled (notification that checkin was created)
 '41f78d9f-95d1-45c4-bad2-ec53fcddc017', -- Offender SMS template
 '3806414e-083e-410e-825a-76e2c72bbd8b', -- Offender Email template
 null, 'PRACTITIONER_CHECKIN_CREATED_EMAIL_TEMPLATE', -- Practitioner Email template (needs GOV.UK Notify template ID)
 NOW(), 'SYSTEM'),

-- Checkin Submitted
('CHECKIN_SUBMITTED',
 true, true,  -- Offender: SMS + Email (confirmation)
 false, true, -- Practitioner: Email enabled (notification to review)
 '80695bae-3917-436a-824b-c61ce04ca4a3', -- Offender SMS
 '8558a963-0d76-4ad5-82d3-3eb536c76563', -- Offender Email
 null, 'PRACTITIONER_CHECKIN_SUBMITTED_EMAIL_TEMPLATE', -- Practitioner Email template (needs GOV.UK Notify template ID)
 NOW(), 'SYSTEM'),

-- Checkin Reviewed
('CHECKIN_REVIEWED',
 false, false, -- Offender: Disabled
 false, false, -- Practitioner: Disabled (no notification needed after review)
 null, null,
 null, null,
 NOW(), 'SYSTEM'),

-- Checkin Expired
('CHECKIN_EXPIRED',
 false, false, -- Offender: Disabled
 false, true, -- Practitioner: Email enabled (notification about expired checkin)
 null, null,
 null, 'PRACTITIONER_CHECKIN_EXPIRED_EMAIL_TEMPLATE', -- Practitioner Email template (needs GOV.UK Notify template ID)
 NOW(), 'SYSTEM');

-- changeset denis:11_create_v2_tables-9 splitStatements:false
-- Create V2 audit table for reporting and analytics
CREATE TABLE IF NOT EXISTS "event_audit_log_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    -- Event Info
    "event_type" VARCHAR(100) NOT NULL,
    "occurred_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- Offender Reference (not PII)
    "crn" VARCHAR(7) NOT NULL,

    -- Practitioner Context (organizational data, not PII)
    "practitioner_id" VARCHAR(255),

    -- Location Hierarchy (snapshot at time of event)
    "local_admin_unit_code" VARCHAR(50),
    "local_admin_unit_description" VARCHAR(255),
    "pdu_code" VARCHAR(50),
    "pdu_description" VARCHAR(255),
    "provider_code" VARCHAR(50),
    "provider_description" VARCHAR(255),

    -- Checkin Reference (if applicable)
    "checkin_uuid" UUID,
    "checkin_status" VARCHAR(50),
    "checkin_due_date" DATE,

    -- Performance Metrics (calculated at time of event)
    "time_to_submit_hours" DECIMAL(10,2),
    "time_to_review_hours" DECIMAL(10,2),
    "review_duration_hours" DECIMAL(10,2),

    -- ID Check Results
    "auto_id_check_result" VARCHAR(50),
    "manual_id_check_result" VARCHAR(50),

    -- Notes (for edge cases until we have proper schema)
    "notes" TEXT,

    CONSTRAINT "event_audit_log_v2_pkey" PRIMARY KEY ("id")
);

-- Indexes for Common Queries
CREATE INDEX "idx_audit_v2_occurred_at" ON "event_audit_log_v2" ("occurred_at");
CREATE INDEX "idx_audit_v2_event_type" ON "event_audit_log_v2" ("event_type");
CREATE INDEX "idx_audit_v2_crn" ON "event_audit_log_v2" ("crn");
CREATE INDEX "idx_audit_v2_practitioner" ON "event_audit_log_v2" ("practitioner_id");
CREATE INDEX "idx_audit_v2_lau_code" ON "event_audit_log_v2" ("local_admin_unit_code");
CREATE INDEX "idx_audit_v2_pdu_code" ON "event_audit_log_v2" ("pdu_code");
CREATE INDEX "idx_audit_v2_provider_code" ON "event_audit_log_v2" ("provider_code");
CREATE INDEX "idx_audit_v2_checkin_uuid" ON "event_audit_log_v2" ("checkin_uuid");
CREATE INDEX "idx_audit_v2_checkin_status" ON "event_audit_log_v2" ("checkin_status");
CREATE INDEX "idx_audit_v2_crn_occurred" ON "event_audit_log_v2" ("crn", "occurred_at");
