--liquibase formatted sql

--changeset dave.iles:13_add_offender_event_log-1 splitStatements:false
CREATE TABLE IF NOT EXISTS "offender_event_log_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "comment" TEXT,
    "created_at" TIMESTAMP(6) WITH TIME ZONE,
    "log_entry_type" VARCHAR(255) NOT NULL,
    "practitioner" VARCHAR(255),
    "uuid" UUID NOT NULL,
    "checkin" BIGINT,
    "offender_id" BIGINT,
    CONSTRAINT "offender_event_log_v2_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk_offender_event_log_v2_offender" FOREIGN KEY ("offender_id") REFERENCES "offender_v2" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_offender_event_log_v2_checkin" FOREIGN KEY ("checkin") REFERENCES "offender_checkin_v2" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "idx_offender_event_log_v2_id" UNIQUE(uuid),
    CONSTRAINT "offender_event_log_v2_log_entry_type_check" CHECK (log_entry_type IN ('OFFENDER_SETUP_COMPLETE','OFFENDER_DEACTIVATED',
       'OFFENDER_CHECKIN_NOT_SUBMITTED','OFFENDER_CHECKIN_REVIEW_SUBMITTED','OFFENDER_CHECKIN_UPDATED',
       'OFFENDER_CHECKIN_RESCHEDULED','OFFENDER_CHECKIN_OUTSIDE_ACCESS'))
    );

--changeset dave.iles:13_add_offender_event_log-2 splitStatements:false
CREATE INDEX IF NOT EXISTS "idx_offender_event_log_v2_entry_type" ON "offender_event_log_v2" ("log_entry_type");

--changeset dave.iles:13_add_offender_event_log-3 splitStatements:false
CREATE INDEX IF NOT EXISTS "idx_offender_event_log_v2_checkin" ON "offender_event_log_v2" ("checkin");