--liquibase formatted sql

--changeset rob.catton:19_create_feedback_table.sql
CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback JSONB NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);