-- liquibase formatted sql

-- changeset roland:21_add_migration_control_tables splitStatements:false
create table migration_control(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "crn" text not null,
    "offender_events" boolean default false,
    "checkin_created" boolean default false,
    "checkin_submitted" boolean default false,
    "checkin_reviewed" boolean default false,
    "checkin_expired" boolean default false
);
-- rollback drop table migration_control;