--liquibase formatted sql

--changeset roland.sadowski:41_custom_questions-1 splitStatements:false

create type response_format as enum ('TEXT', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE');

create type text_language as enum ('en-GB', 'cy-GB');

-- FIXED: practitioner can't choose whether the question will be presented to the user
-- CUSTOMISABLE: practitioner can choose whether the question will be presented to the user
create type question_policy as enum ('FIXED', 'CUSTOMISABLE');

create table question(
    id bigint generated by default as identity primary key,
    author varchar(255) not null,
    policy question_policy not null default 'FIXED',
    created_at timestamp with time zone not null default now()
);

create table question_info(
    id bigint generated by default as identity primary key,
    question_id bigint not null references question(id) on delete cascade,
    lang text_language not null default 'en-GB',
    -- question_template: can contain placeholders, e.g. "How did {{placeholder1}} go?"
    question_template text not null,
    response_format response_format not null,
    -- response_format == 'TEXT' -> {"placeholders": ["placeholder1", "placeholder2"]}
    -- response_format == 'SINGLE_CHOICE' -> {"placeholders": ["placeholder1"], "choices": ["option1", "option2"]}
    -- response_format == 'MULTIPLE_CHOICE' -> {"placeholders": ["placeholder1"], "choices": ["option1", "option2"]}
    response_spec jsonb,
    example text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    constraint question_text_unique_question_lang unique (question_id, lang)
    --constraint question_info_pk primary key (question_id, lang)
);

create index question_policy_idx on question (policy);
create index question_text_lang_idx on question_info (lang);

--rollback:
--rollback drop index question_text_lang_idx;
--rollback drop index question_policy_idx;
--rollback drop table question_info;
--rollback drop table question;
--rollback drop type response_format;
--rollback drop type text_language;
--rollback drop type question_policy;

--changeset roland.sadowski:41_custom_questions-2 splitStatements:false

create table question_list(
    id bigint generated by default as identity primary key,
    author varchar(255) not null,
    comment text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

--rollback drop table questions_list;

--changeset roland.sadowski:41_custom_questions-3 splitStatements:false

create table question_list_item(
    question_list_id bigint not null references question_list(id) on delete cascade,
    question_id bigint not null references question(id) on delete cascade,
    "position" int not null,
    -- if response_format == 'TEXT' -> {"placeholders": {"placeholder1": "value1", "placeholder2": "value2"}}
    -- if response_format == 'SINGLE_CHOICE' -> {"placeholders": {"placeholder1": "option1", "placeholder2": "option2"}}
    -- if response_format == 'MULTIPLE_CHOICE' -> {"placeholders": {"placeholder1": "option1", "placeholder2": "option2"}}
    params jsonb,

    constraint question_list_item_pk primary key (question_list_id, question_id, "position")
);

--rollback drop table question_list_item;

--changeset roland.sadowski:41_custom_questions-3.1 splitStatements:false

create table question_list_assignment(
    id bigint generated always as identity primary key,
--     question_list_id bigint not null references question_list(id) on delete cascade,
--     offender_id bigint not null references offender(id) on delete cascade,
--     checkin_id bigint references checkin(id) on delete cascade,
    question_list_id bigint not null,
    offender_id bigint not null,
    checkin_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create unique index idx_single_pending_assignment_per_offender
on question_list_assignment (offender_id)
where checkin_id is null;

--changeset roland.sadowski:41_custom_questions-4 splitStatements:false

set esup_41_custom_questions.default_list_id = '1';

-- creates/updates a question list for already existing questions
create or replace function upsert_custom_question_list(
    p_question_list_id bigint,
    p_author varchar(255),
    p_questions jsonb
)
    returns int
    language plpgsql
as $$
declare
    v_question_list_id int;
begin
    if p_questions is null or jsonb_typeof(p_questions) <> 'array' then
        raise exception 'p_questions must be a JSONB array of objects like {"id": 1, "params": {}} TODO! put schema name here';
    end if;

    if p_question_list_id = current_setting('esup_41_custom_questions.default_list_id')::bigint then
        raise exception 'Cannot update default question list';
    end if;

    if p_question_list_id is null then
        insert into question_list(author)
        values (p_author)
        returning id into v_question_list_id;
    else
        v_question_list_id := p_question_list_id;

        update question_list
        set author = coalesce(p_author, author)
        where id = v_question_list_id;
    end if;

    delete from question_list_item
    where question_list_id = v_question_list_id;

    -- insert in the order of the JSON array
    insert into question_list_item(
        question_list_id,
        question_id,
        "position",
        params
    )
    select
        v_question_list_id,
        (q_elem->>'id')::int as question_id,
        q_ord as "position",
        coalesce(q_elem->'params', '{}'::jsonb) as params
    from jsonb_array_elements(p_questions) with ordinality as x(q_elem, q_ord)
    where q_elem ? 'id';

    return v_question_list_id;
end;
$$;

--rollback drop function upsert_custom_question_list;

--changeset roland.sadowski:41_custom_questions-5 splitStatements:false

create or replace function validate_question_localisations()
    returns trigger
    language plpgsql
as $$
declare
    q_id bigint;
    lang_count int;
    has_en boolean;
    has_cy boolean;
begin
    q_id := coalesce(new.id, old.id);

    select
        count(*)::int,
        bool_or(lang = 'en-GB'),
        bool_or(lang = 'cy-GB')
    into
        lang_count,
        has_en,
        has_cy
    from question_info qi
    where qi.question_id = q_id;

    if new.author = 'SYSTEM' and lang_count <> 2 or not has_en or not has_cy then
        raise exception
            'question % must have exactly two translations: en-GB and cy-GB',
            q_id;
    end if;

    return null;
end;
$$;

create constraint trigger question_localisation_check_from_question
    after insert or update of author
    on question
    deferrable initially deferred
    for each row
execute function validate_question_localisations();

--changeset roland.sadowski:41_custom_questions-5.1 splitStatements:false

-- we want any pending question list assignments to reference the checkin once its status changes
CREATE OR REPLACE FUNCTION fn_update_question_assignment()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status = 'CREATED'::offender_checkin_status_v2 AND NEW.status IS DISTINCT FROM 'CREATED'::offender_checkin_status_v2 THEN
        UPDATE question_list_assignment
        SET checkin_id = NEW.id
        WHERE checkin_id IS NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_checkin_status_change
AFTER UPDATE ON offender_checkin_v2
FOR EACH ROW
WHEN (OLD.status = 'CREATED'::offender_checkin_status_v2 and OLD.STATUS IS DISTINCT FROM NEW.status)
EXECUTE FUNCTION fn_update_question_assignment();

--changeset roland.sadowski:41_custom_questions-6 splitStatements:false

create or replace function get_question_list(p_list_id bigint, p_lang text_language)
returns table (
        question_id bigint,
        question_template text,
        response_format response_format,
        response_spec jsonb,
        params jsonb,
        "position" int,
        section int
) as $$
begin
    return query
    select q.id,
           qi.question_template, qi.response_format, qi.response_spec,
           qli.params, qli.position as "position",
           1 as section
    from question q
             join question_info qi on q.id = qi.question_id
             join question_list_item qli on q.id = qli.question_id
    where qli.question_list_id = 1 and qi.lang = p_lang
    union select
        q.id,
        qi.question_template, qi.response_format, qi.response_spec,
        qli.params, qli.position as "position",
        2 as section
    from question q
             join question_info qi on q.id = qi.question_id
             join question_list_item qli on q.id = qli.question_id
    where qli.question_list_id = p_list_id and qli.question_list_id <> 1 and qi.lang = p_lang
    order by section, "position";
end;
$$ LANGUAGE plpgsql STABLE;

--rollback drop function get_question_list;

--changeset roland.sadowski:41_custom_questions-7 splitStatements:false

create or replace function define_system_question(
    p_response_format response_format,
    en_question_template text,
    en_spec jsonb,
    cy_question_template text,
    cy_spec jsonb
) returns bigint as $$
declare
    new_question_id bigint;
begin
    insert into question (author)
    values ('SYSTEM')
    returning id into new_question_id;

    insert into question_info (
        question_id,
        lang,
        question_template,
        response_format,
        response_spec
    )
    select
        new_question_id,
        q.lang,
        q.template,
        p_response_format,
        q.spec
    from (
             values
                 ('en-GB'::text_language, en_question_template, en_spec),
                 ('cy-GB'::text_language, cy_question_template, cy_spec)
         ) as q(lang, template, spec);

    return new_question_id;
end;
$$ language plpgsql;

--rollback drop function define_system_question;

--changeset roland.sadowski:41_custom_questions-8 splitStatements:false

create or replace function define_custom_question(
    p_author varchar(255),
    en_question_template text default null,
    en_spec jsonb default null,
    cy_question_template text default null,
    cy_spec jsonb default null
) returns integer as $$
declare
    new_question_id integer;
begin
    insert into question (author, policy)
    values (p_author, 'CUSTOMISABLE'::question_policy)
    returning id into new_question_id;

    insert into question_info (
        question_id,
        lang,
        question_template,
        response_format,
        response_spec
    )
    select
        new_question_id,
        q.lang,
        q.template,
        'TEXT'::response_format,
        q.spec
    from (
             values
                 ('en-GB'::text_language, en_question_template, en_spec),
                 ('cy-GB'::text_language, cy_question_template, cy_spec)
         ) as q(lang, template, spec)
    where q.template is not null; -- This ensures only provided versions are saved

    if not exists (select 1 from question_info where question_id = new_question_id) then
        raise exception 'At least one localization (EN or CY) must be provided.';
    end if;

    return new_question_id;
end;
$$ language plpgsql;

--rollback drop function define_custom_question;

--changeset roland.sadowski:41_custom_questions-9 splitStatements:false

do $main$
declare
    q_mandatory_1 bigint;
    q_mandatory_2 bigint;
    q_mandatory_3 bigint;
begin
q_mandatory_1 := define_system_question(
               'MULTIPLE_CHOICE'::response_format,
               'Is there anything you need support with or want to let us know about?',
               $${
                 "placeholders": [],
                 "label": "Is there anything you need support with or want to let us know about?",
                 "hint": "This could be anything you're worrying about, struggling with or just want to let us know.",
                 "domain_msg_head": "What they want us to know about thing",
                 "choices": [
                        {
                          "id": "MENTAL_HEALTH",
                          "label": "Mental health",
                          "details_label": "Tell us what you want us to know about mental health (optional)",
                          "details_id": "??",
                          "domain_msg_head": ""
                       },
                       {
                         "id": "ALCOHOL",
                         "label": "Alcohol",
                         "details_label": "Tell us what you want us to know about alcohol (optional)",
                         "details_id": "??",
                         "domain_msg_head": ""
                       },
                       {
                         "id": "DRUGS",
                         "label": "Drugs",
                         "details_label": "Tell us what you want us to know about drugs (optional)",
                         "details_id": "??",
                         "domain_msg_head": ""
                       },
                       {
                         "id": "MONEY",
                         "label": "Money",
                         "details_label": "Tell us what you want us to know about money (optional)",
                         "details_id": "??",
                         "domain_msg_head": ""
                       },
                       {
                         "id": "HOUSING",
                         "label": "Housing",
                         "details_label": "Tell us what you want us to know about housing (optional)",
                         "details_id": "??",
                         "domain_msg_head": ""
                       },
                       {
                         "id": "SUPPORT_SYSTEM",
                         "label": "Support system (family, relationships, friends)",
                         "details_label": "Tell us what you want us to know about your support system (optional)",
                         "details_id": "??",
                         "domain_msg_head": ""
                       },
                       {
                         "id": "OTHER",
                         "label": "Something else",
                         "details_label": "Tell us what you want us to know about (optional)",
                         "details_id": "??",
                         "domain_msg_head": ""
                       }
                   ],
                   "alternative": {
                         "id": "DRUGS",
                         "label": "No, I do not need help",
                         "details_label": null,
                         "details_id": null,
                         "domain_msg_head": "They don't need help"
                   }
               }$$::jsonb,
                -- cy-GB
               'Is there anything you need support with or want to let us know about?',
               $${
                 "placeholders": [],
                 "label": "Is there anything you need support with or want to let us know about?",
                 "hint": "This could be anything you're worrying about, struggling with or just want to let us know.",
                 "domain_msg_head": "What they want us to know about thing",
                 "choices": [
                   {
                     "id": "MENTAL_HEALTH",
                     "label": "Mental health",
                     "details_label": "Tell us what you want us to know about mental health (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "ALCOHOL",
                     "label": "Alcohol",
                     "details_label": "Tell us what you want us to know about alcohol (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "DRUGS",
                     "label": "Drugs",
                     "details_label": "Tell us what you want us to know about drugs (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "MONEY",
                     "label": "Money",
                     "details_label": "Tell us what you want us to know about money (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "HOUSING",
                     "label": "Housing",
                     "details_label": "Tell us what you want us to know about housing (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "SUPPORT_SYSTEM",
                     "label": "Support system (family, relationships, friends)",
                     "details_label": "Tell us what you want us to know about your support system (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "OTHER",
                     "label": "Something else",
                     "details_label": "Tell us what you want us to know about (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   }
                 ],
                 "alternative": {
                   "id": "DRUGS",
                   "label": "No, I do not need help",
                   "details_label": null,
                   "details_id": null,
                   "domain_msg_head": "They don't need help"
                 }
               }$$::jsonb
       );

q_mandatory_2 := define_system_question(
               'SINGLE_CHOICE'::response_format,
               'How have you been feeling since we last spoke?',
               $${
                 "placeholders": [],
                 "label": "Is there anything you need support with or want to let us know about?",
                 "hint": "Think about things like if you have noticed a change in your mood and what may have caused this. ",
                 "message": {
                   "html": "If you need to speak to someone urgently about how you are feeling, check the <a href=\"https://www.nhs.uk/mental-health/feelings-symptoms-behaviours/behaviours/help-for-suicidal-thoughts/\" class=\"govuk-link\" target=\"_blank\">NHS website for help (opens in new tab)</a>."
                 },
                 "domain_msg_head": "TODO",
                 "choices": [
                   {
                     "id": "VERY_WELL",
                     "label": "Very well",
                     "details_label": "Tell us why you are very well (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "WELL",
                     "label": "Well",
                     "details_label": "Tell us why you are well (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "OK",
                     "label": "OK",
                     "details_label": "Tell us why you are OK (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "NOT_GREAT",
                     "label": "Not great",
                     "details_label":  "Tell us why you are not great (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "STRUGGLING",
                     "label": "Struggling",
                     "details_label": "Tell us why you are struggling (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   }
                 ]
               }$$::jsonb,
               -- cy-GB
               'How have you been feeling since we last spoke?',
               $${
                 "placeholders": [],
                 "label": "Is there anything you need support with or want to let us know about?",
                 "hint": "Think about things like if you have noticed a change in your mood and what may have caused this. ",
                 "message": {
                   "html": "If you need to speak to someone urgently about how you are feeling, check the <a href=\"https://www.nhs.uk/mental-health/feelings-symptoms-behaviours/behaviours/help-for-suicidal-thoughts/\" class=\"govuk-link\" target=\"_blank\">NHS website for help (opens in new tab)</a>."
                 },
                 "domain_msg_head": "TODO",
                 "choices": [
                   {
                     "id": "VERY_WELL",
                     "label": "Very well",
                     "details_label": "Tell us why you are very well (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "WELL",
                     "label": "Well",
                     "details_label": "Tell us why you are well (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "OK",
                     "label": "OK",
                     "details_label": "Tell us why you are OK (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "NOT_GREAT",
                     "label": "Not great",
                     "details_label":  "Tell us why you are not great (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   },
                   {
                     "id": "STRUGGLING",
                     "label": "Struggling",
                     "details_label": "Tell us why you are struggling (optional)",
                     "details_id": "??",
                     "domain_msg_head": ""
                   }
                 ]
               }$$::jsonb
       );

q_mandatory_3 := define_system_question(
        'SINGLE_CHOICE'::response_format,
        'Would you like us to contact you about anything before your next appointment?',
        $${
          "placeholders": [],
          "label": "Is there anything you need support with or want to let us know about?",
          "hint": "Think about things like if you have noticed a change in your mood and what may have caused this. ",
          "message": {
            "html": "If you need to speak to someone urgently about how you are feeling, check the <a href=\"https://www.nhs.uk/mental-health/feelings-symptoms-behaviours/behaviours/help-for-suicidal-thoughts/\" class=\"govuk-link\" target=\"_blank\">NHS website for help (opens in new tab)</a>."
          },
          "domain_msg_head": "TODO",
          "choices": [
            {
              "id": "Yes",
              "label": "Yes",
              "details_label": "This could be something you've already asked for help with or something new.",
              "details_id": "??",
              "domain_msg_head": ""
            },
            {
              "id": "NO",
              "label": "No",
              "details_label": null,
              "details_id": null,
              "domain_msg_head": ""
            }
          ]
        }$$::jsonb,
    -- cy-GB
        'Would you like us to contact you about anything before your next appointment?',
        $${
          "placeholders": [],
          "label": "Is there anything you need support with or want to let us know about?",
          "hint": "Think about things like if you have noticed a change in your mood and what may have caused this. ",
          "message": {
            "html": "If you need to speak to someone urgently about how you are feeling, check the <a href=\"https://www.nhs.uk/mental-health/feelings-symptoms-behaviours/behaviours/help-for-suicidal-thoughts/\" class=\"govuk-link\" target=\"_blank\">NHS website for help (opens in new tab)</a>."
          },
          "domain_msg_head": "TODO",
          "choices": [
            {
              "id": "Yes",
              "label": "Yes",
              "details_label": "This could be something you've already asked for help with or something new.",
              "details_id": "??",
              "domain_msg_head": ""
            },
            {
              "id": "NO",
              "label": "No",
              "details_label": null,
              "details_id": null,
              "domain_msg_head": ""
            }
          ]
        }$$::jsonb
);

-- defines the default question list that every checkin will require by default.
-- If the practitioner adds custom questions to a checkin, they
insert into question_list(id, author, comment)
values (current_setting('esup_41_custom_questions.default_list_id')::bigint,'SYSTEM', 'Default question list');

perform
    setval(
            pg_get_serial_sequence('question_list', 'id'),
            COALESCE(MAX(id), 0) + 1,
            false
    )
from question_list;

insert into question_list_item(question_list_id, question_id, "position", params)
values (current_setting('esup_41_custom_questions.default_list_id')::bigint,
        q_mandatory_1, 1, $${}$$::jsonb);
insert into question_list_item(question_list_id, question_id, "position", params)
values (current_setting('esup_41_custom_questions.default_list_id')::bigint,
        q_mandatory_2, 2, $${}$$::jsonb);
insert into question_list_item(question_list_id, question_id, "position", params)
values (current_setting('esup_41_custom_questions.default_list_id')::bigint,
        q_mandatory_3, 3, $${}$$::jsonb);

perform define_custom_question(
        'SYSTEM',
        'Did you finish {{thing}}?',
        $${
         "placeholders": [ "thing" ],
         "label": "Label for did you finish this thing?",
         "hint": "Hint for the question",
         "domain_msg_head": "Did they finish this thing?"}$$::jsonb,
        -- cy-GB
        'Bork bork bork {{thing}}?',
        $${
          "placeholders": [ "thing" ],
          "label": "Label for did you finish this thing?",
          "hint": "Hint for the question",
          "domain_msg_head": "Did they finish this thing?"}$$::jsonb
        );

end $main$;

--rollback:
--rollback delete from question_list_item;
--rollback delete from question_list;
--rollback delete from question_info;
--rollback delete from question;

--changeset roland.sadowski:41_custom_questions-10 splitStatements:false

create or replace function get_question_templates(p_lang text_language, p_author varchar(255))
    returns table (
                      question_id bigint,
                      question_template text,
                      response_format response_format,
                      response_spec jsonb
                  ) as $$
begin
    return query
        select
            q.id,
            qi.question_template, qi.response_format, qi.response_spec
        from question q
        join question_info qi on q.id = qi.question_id
        where
            qi.lang = p_lang
          and q.author = p_author
          and q.policy = 'CUSTOMISABLE'::question_policy
        order by q.created_at;
end;
$$ LANGUAGE plpgsql STABLE;

--rollback drop function get_question_templates;
