-- liquibase formatted sql

-- changeset richard-birch:57_setup_event_backfill_v2-1 splitStatements:false
CREATE TABLE IF NOT EXISTS "setup_event_backfill_v2" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "offender_id" BIGINT NOT NULL CONSTRAINT "uk_setup_event_backfill_v2_offender" UNIQUE,
    "setup_row_created" BOOLEAN NOT NULL DEFAULT false,
    "event_sent" BOOLEAN NOT NULL DEFAULT false,
    "event_sent_at" TIMESTAMP(6) WITH TIME ZONE,
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT "setup_event_backfill_v2_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk_setup_event_backfill_v2_offender" FOREIGN KEY ("offender_id") REFERENCES "offender_v2" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX "idx_setup_event_backfill_v2_event_sent" ON "setup_event_backfill_v2" ("event_sent") WHERE event_sent = false;
CREATE INDEX "idx_setup_event_backfill_v2_setup_created" ON "setup_event_backfill_v2" ("setup_row_created") WHERE setup_row_created = false;

-- rollback DROP TABLE "setup_event_backfill_v2";

-- changeset richard-birch:57_setup_event_backfill_v2-2 splitStatements:false
INSERT INTO "setup_event_backfill_v2" ("offender_id")
SELECT o.id FROM "offender_v2" o
WHERE o.status = 'VERIFIED'
ON CONFLICT ("offender_id") DO NOTHING;

-- rollback DELETE FROM "setup_event_backfill_v2";
