--liquibase formatted sql

--changeset roland.sadowski:58_ndelius_notification_outbox-1 splitStatements:false

create type OutboxItemStatus as enum ('INITIAL', 'SENT');

create type OutboxItemType as enum (
    'OFFENDER_SETUP_COMPLETE',
    'OFFENDER_DEACTIVATED',
    'CHECKIN_CREATED',
    'CHECKIN_SUBMITTED',
    'CHECKIN_REVIEWED',
    'CHECKIN_EXPIRED'
);

create table outbox_items(
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "type" OutboxItemType not null,
    "entity_id" bigint not null,
    "status" OutboxItemStatus not null default 'INITIAL'::OutboxItemStatus,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,

    unique ("type", "entity_id")
);

--rollback:
--rollback drop table if exists outbox_items;
--rollback drop type OutboxItemType;
--rollback drop type OutboxItemStatus;

--changeset roland.sadowski:58_ndelius_notification_outbox-2 splitStatements:false

CREATE OR REPLACE FUNCTION fn_add_outbox_record_on_checkin_status_update()
    RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO outbox_items(type, entity_id)
    VALUES (
            CASE
                WHEN NEW.status = 'SUBMITTED'::offender_checkin_status_v2 THEN 'CHECKIN_SUBMITTED'::OutboxItemType
                WHEN NEW.status = 'REVIEWED'::offender_checkin_status_v2  THEN 'CHECKIN_REVIEWED'::OutboxItemType
                --WHEN NEW.STATUS = 'EXPIRED'::offender_checkin_status_v2 THEN 'CHECKIN_EXPIRED'::OutboxItemType
            END,
            NEW.id
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_checkin_status_change__outbox
    AFTER UPDATE on offender_checkin_v2
    FOR EACH ROW
    WHEN (NEW.status <> OLD.status and NEW.status in ('SUBMITTED'::offender_checkin_status_v2, 'REVIEWED'::offender_checkin_status_v2))
EXECUTE FUNCTION fn_add_outbox_record_on_checkin_status_update();

--rollback:
--rollback drop trigger if exists trg_checkin_status_change__outbox on offender_checkin_v2;
--rollback drop function if exists fn_add_outbox_record_on_checkin_status_update;