-- liquibase formatted sql

-- changeset richard-birch:71_checkin_note_resend-1 splitStatements:false
CREATE TABLE IF NOT EXISTS "checkin_note_resend" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "checkin" UUID NOT NULL CONSTRAINT "uk_checkin_note_resend_checkin" UNIQUE,
    "annotation_uuid" UUID,
    "sent_at" TIMESTAMP(6) WITH TIME ZONE,
    "notes" TEXT,
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT "checkin_note_resend_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "idx_checkin_note_resend_pending" ON "checkin_note_resend" ("id") WHERE sent_at IS NULL;

-- rollback DROP TABLE IF EXISTS "checkin_note_resend";

-- changeset richard-birch:71_checkin_note_resend-2 runInTransaction:false
ALTER TYPE job_type_v2 ADD VALUE 'CHECKIN_NOTE_RESEND';

-- rollback:
-- No easy way to remove enum value in Postgres without dropping and recreating the type,
-- which is dangerous. Leaving it as is.
