--liquibase formatted sql

--changeset roland.sadowski:74_offender_eligibility_rules-1 splitStatements:false

create type eligibility_operator as enum ('IS_NULL', 'IS_NOT_NULL', 'EQUALS');

create type eligibility_rule_outcome as enum ('CONTINUE', 'ELIGIBLE', 'NOT_ELIGIBLE');

create table offender_eligibility_rule(
    id bigint generated by default as identity primary key,
    rule_set varchar(64) not null default 'OFFENDER_ELIGIBILITY',
    rule_order double precision not null,
    code varchar(64) not null,
    question text not null,
    source varchar(32) not null,
    data_point varchar(128) not null,
    operator eligibility_operator not null,
    comparison_value text,
    outcome_on_match eligibility_rule_outcome not null,
    message_on_match text,
    outcome_on_no_match eligibility_rule_outcome not null,
    message_on_no_match text,
    enabled boolean not null default true,
    comment text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    constraint offender_eligibility_rule_order_unique unique (rule_set, rule_order),
    constraint offender_eligibility_rule_code_unique unique (rule_set, code),
    constraint offender_eligibility_rule_match_message_check
        check ((outcome_on_match = 'CONTINUE') = (message_on_match is null)),
    constraint offender_eligibility_rule_no_match_message_check
        check ((outcome_on_no_match = 'CONTINUE') = (message_on_no_match is null))
);

create index idx_offender_eligibility_rule_lookup
    on offender_eligibility_rule (rule_set, enabled, rule_order);

--rollback:
--rollback drop index idx_offender_eligibility_rule_lookup;
--rollback drop table offender_eligibility_rule;
--rollback drop type eligibility_rule_outcome;
--rollback drop type eligibility_operator;

--changeset roland.sadowski:74_offender_eligibility_rules-2

insert into offender_eligibility_rule
  (rule_order, code, question, source, data_point, operator, comparison_value,
   outcome_on_match, message_on_match, outcome_on_no_match, message_on_no_match, comment)
values
  -- rules for default rule set are not final, and for illustrative purposes only, atm.
  (1, 'IS_ALIVE', 'Is the person alive?', 'NDELIUS', 'DECEASED_DATE', 'IS_NULL', null,
   'CONTINUE', null, 'NOT_ELIGIBLE', 'The person is deceased', null),
  (2, 'HAS_ACTIVE_EVENT', 'Do they have an active sentence?', 'NDELIUS', 'ACTIVE_EVENT', 'IS_NOT_NULL', null,
   'CONTINUE', null, 'NOT_ELIGIBLE', 'No active sentence.', null);

insert into offender_eligibility_rule
(rule_set, rule_order, code, question, source, data_point, operator, comparison_value,
 outcome_on_match, message_on_match, outcome_on_no_match, message_on_no_match, comment)
values
    ('PILOT_2026_08', 1, 'HAS_ACTIVE_EVENT', 'Do they have an active sentence?', 'NDELIUS', 'ACTIVE_EVENT', 'IS_NOT_NULL', null,
     'CONTINUE', null, 'NOT_ELIGIBLE', 'there are no active probation events in NDelius', null),
    ('PILOT_2026_08', 2, 'IS_CONTACT_SUSPENDED', 'Are they in reset?', 'NDELIUS', 'CONTACT_SUSPENDED', 'EQUALS', 'false',
     'CONTINUE', null, 'NOT_ELIGIBLE', 'contact is suspended (in reset) in NDelius', null);

--rollback delete from offender_eligibility_rule;
