--liquibase formatted sql

--changeset roland.sadowski:76_offender_eligibility_check-1 splitStatements:false

create type eligibility_check_outcome as enum ('ELIGIBLE', 'INELIGIBLE', 'DATA_UNAVAILABLE');

create table offender_eligibility_check(
    id bigint generated by default as identity primary key,
    offender_id bigint not null references offender_v2(id),
    rule_set varchar(64) not null,
    outcome eligibility_check_outcome not null,
    message text,
    triggered_rule_code varchar(64),
    checked_at timestamp with time zone not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    constraint offender_eligibility_check_offender_rule_set_unique unique (offender_id, rule_set)
);

create index idx_offender_eligibility_check_offender on offender_eligibility_check (offender_id);

--rollback:
--rollback drop index idx_offender_eligibility_check_offender;
--rollback drop table offender_eligibility_check;
--rollback drop type eligibility_check_outcome;
