# curl -X POST "http://localhost:8090/auth/oauth/token?grant_type=client_credentials" -H "Authorization:Basic $(echo -n 'hmpps-typescript-template-system:clientsecret' | base64)"
### Get Auth
POST http://localhost:8090/auth/oauth/token?grant_type=client_credentials
Authorization: Basic aG1wcHMtdHlwZXNjcmlwdC10ZW1wbGF0ZS1zeXN0ZW06Y2xpZW50c2VjcmV0

> {% client.global.set("auth_token", jsonPath(response.body, "access_token")) %}

#### GET offender invites
GET http://localhost:8080/example/time
Authorization: Bearer {{auth_token}}
