### Get all feedback
GET {{HOST}}/v2/feedback
Authorization: Bearer {{hmpps_auth.token}}

> {%
    console.log("response body", response.body)
 %}

### Create some feedback
POST {{HOST}}/v2/feedback
Authorization: Bearer {{hmpps_auth.token}}
Content-Type: application/json

{
    "feedback": {
      "version": 1,
      "howEasy": "veryEasy",
      "gettingSupport": "yes",
      "improvements": ["findingOutAboutCheckIns", "textOrEmailNotifications", "somethingElse"]
    }
}
> {%
    console.log("response body", response.body)
 %}