@practitioner_uuid = 1ba848cf-0fb8-4d24-868c-390a8c0bdb00

### Get offender info
GET {{HOST}}/offenders?practitionerUuid={{practitioner_uuid}}
Authorization: Bearer {{hmpps_auth.token}}

> {%
    const offenderUuid = response.body["content"][0].uuid
    console.log("offender uuid", offenderUuid)
    client.global.set("offender_uuid", offenderUuid)
 %}

### See existing checkins
GET {{HOST}}/offender_checkins?practitionerUuid={{practitioner_uuid}}
Authorization: Bearer {{hmpps_auth.token}}

> {%
    client.test("successful response", () => {
        response.status === 200
    })
 %}


### Create a checkin
POST {{HOST}}/offender_checkins
Authorization: Bearer {{hmpps_auth.token}}
Content-Type: application/json

{
    "practitioner": "{{practitioner_uuid}}",
    "offender": "{{offender_uuid}}",
    "dueDate": "2025-07-20"
}

> {%
    if (response.status === 200) {
        const checkinUuid = response.body["uuid"]
        console.log("checkin uuid", checkinUuid)
        client.global.set("checkin_uuid", checkinUuid)
    }
%}

### Request upload location for the offender
POST {{HOST}}/offender_checkins/{{checkin_uuid}}/upload_location
    ?video=video/mp4
    &snapshots=image/png
    &reference=image/png
Authorization: Bearer {{hmpps_auth.token}}

> {%
    if (response.status === 200) {
        const uploadUrl = response.body["locationInfo"]["url"]
        client.log("upload url: ", uploadUrl)
        client.global.set("checkinVideoUploadUrl", uploadUrl)
    }
%}

### Upload the video
PUT {{checkinVideoUploadUrl}}
Content-Type: image/png

< ./guy.png


### Submit the checkin
POST {{HOST}}/offender_checkins/{{checkin_uuid}}/submit
Authorization: Bearer {{hmpps_auth.token}}
Content-Type: application/json

{
  "offender": "{{offender_uuid}}",
  "survey": {"mood":  "OK"}
}

### Review the checkin
POST {{HOST}}/offender_checkins/{{checkin_uuid}}/review
Authorization: Bearer {{hmpps_auth.token}}
Content-Type: application/json

{
  "practitioner": "{{practitioner_uuid}}",
  "manualIdCheck": "MATCH"
}