### Practitioner invites people to the app

POST http://localhost:8080/offender_invites/
Content-Type: application/json
Authorization: Bearer {{hmpps_auth.pp}}

{
  "invitees": [
    {
      "firstName": "Barry",
      "lastName": "Bronson",
      "dateOfBirth": "1990-01-30",
      "email": "barry@example.com"
    }, {
      "firstName": "Barry",
      "lastName": "B",
      "dateOfBirth": "1990-01-30",
      "email": "barry.b@example.com"
    }]
}

> {%
if (response.status === 200) {
    const invite = response.body["results"][0].invite
    client.log(`created invite with ${invite.uuid}`)
    client.global.set("invite", invite)
}
%}

###
GET http://localhost:8080/offender_invites
Authorization: Bearer {{hmpps_auth.pp}}
Content-Type: application/json

> {%
if (response.status == 200) {

}
 %}

### Offender confirms the invite
POST http://localhost:8080/offender_invites/confirm
Authorization: Bearer {{hmpps_auth.pop}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inviteUuid"

{{invite.uuid}}
--WebAppBoundary
Content-Disposition: form-data; name="info.firstName"

Barry
--WebAppBoundary
Content-Disposition: form-data; name="info.lastName"

Bronson
--WebAppBoundary
Content-Disposition: form-data; name="info.dateOfBirth"

1990-01-30
--WebAppBoundary
Content-Disposition: form-data; name="info.email"

barry@example.com
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./guy.png
--WebAppBoundary--

### Practitioner sees invite status on the dashboard
GET http://localhost:8080/offender_invites
Authorization: Bearer {{hmpps_auth.pp}}

### Practitioner approves invite -> offender record added
POST http://localhost:8080/offender_invites/approve?uuid={{invite.uuid}}
Authorization: Bearer {{hmpps_auth.pp}}


### Let's verify we created an offender record
GET http://localhost:8080/offenders
Authorization: Bearer {{hmpps_auth.pp}}
Content-Type: application/json
