### Practitioner invites people to the app

@practitioner_uuid = b6201c70-510e-11f0-aead-e2c91dd81a06
### Start offender setup

< {%
    const setupUuid = $random.uuid
    request.variables.set('setupUuid', setupUuid)
%}
POST {{HOST}}/offender_setup
Content-Type: application/json
Authorization: Bearer {{hmpps_auth.token}}

{

  "setupUuid": "{{$uuid}}",
  "practitionerId": "{{practitioner_uuid}}",
  "firstName": "Barry",
  "lastName": "Bronson",
  "dateOfBirth": "1990-01-30",
  "email": "barry@example.com"
}


> {%
if (response.status === 200) {
    const offenderUuid = response.body["offender"]
    client.log(`initiated setup uuid=${offenderUuid}`)
    client.global.set("offender_uuid", offenderUuid)
    client.global.set("setup_uuid", response.body["uuid"])
}
%}


### Request upload location for the offender
POST {{HOST}}/offender_setup/{{setup_uuid}}/upload_location?content-type=image/png
Authorization: Bearer {{hmpps_auth.token}}

> {%
if (response.status === 200) {
    const uploadUrl = response.body["locationInfo"]["url"]
    client.global.set("invitePhotoUploadUrl", uploadUrl)
}
%}


### "Attach" photo to the invite
PUT {{invitePhotoUploadUrl}}
Content-Type: image/png

< ./guy.png

#### Practitioner sees invite status on the dashboard
#GET {{HOST}}/offender_setup
#Authorization: Bearer {{hmpps_auth.token}}
#

### Practitioner completes the offender setup process
POST {{HOST}}/offender_setup/{{setup_uuid}}/complete
Authorization: Bearer {{hmpps_auth.token}}


### Let's verify we created an offender record
GET {{HOST}}/offenders
Authorization: Bearer {{hmpps_auth.token}}
Content-Type: application/json


### Maybe we need to terminate a setup process?
POST {{HOST}}/offender_setup/ef0fc397-f45e-4521-852f-2455ab758300/terminate
Authorization: Bearer {{hmpps_auth.token}}