@practitioner_uuid = 67e80fa6-8852-4350-ab39-aa715ebbbeea

## Get practitioner info
GET http://localhost:8080/offenders
Authorization: Bearer {{hmpps_auth.pp}}

> {%
    const offenderUuid = response.body["content"][0].uuid
    console.log("offender uuid", offenderUuid)
    client.global.set("offender_uuid", offenderUuid)
 %}

### See existing checkins
GET http://localhost:8080/offender_checkins
Authorization: Bearer {{hmpps_auth.pp}}

> {%
    client.test("successful response", () => {
        response.status === 200
    })
 %}


### Create a checkin
POST http://localhost:8080/offender_checkins
Authorization: Bearer {{hmpps_auth.pp}}
Content-Type: application/json

{
    "practitioner": "{{practitioner_uuid}}",
    "offender": "{{offender_uuid}}",
    "questions": "What is your favourite colour?",
    "dueDate": "2025-07-14"
}

> {%
    if (response.status === 200) {
        const checkinUuid = response.body["uuid"]
        console.log("checkin uuid", checkinUuid)
        client.global.set("checkin_uuid", checkinUuid)
    }
%}

### Request upload location for the offender
POST http://localhost:8080/offender_checkins/{{checkin_uuid}}/upload_location?content-type=image/png
Authorization: Bearer {{hmpps_auth.pop}}

> {%
    if (response.status === 200) {
        const uploadUrl = response.body["locationInfo"]["url"]
        client.log("upload url: ", uploadUrl)
        client.global.set("checkinVideoUploadUrl", uploadUrl)
    }
%}

### Upload the video
PUT {{checkinVideoUploadUrl}}
Content-Type: image/png

< ./guy.png


### Submit the checkin
POST http://localhost:8080/offender_checkins/{{checkin_uuid}}/submit
Authorization: Bearer {{hmpps_auth.pop}}
Content-Type: application/json

{
  "offender": "{{offender_uuid}}",
  "answers": "yellow"
}

