-- liquibase formatted sql

-- changeset lee.kitching:1757938355304-1 splitStatements:false
CREATE TABLE IF NOT EXISTS "job_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "ended_at" TIMESTAMP(6) WITH TIME ZONE,
    "job_type" VARCHAR(255) NOT NULL,
    CONSTRAINT "job_log_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "job_log_job_type_check" CHECK (job_type IN ('CHECKIN_NOTIFICATIONS_JOB', 'CHECKIN_NOTIFICATION_STATUS_UPDATE_JOB', 'CHECKIN_EXIPIRED_NOTIFICATIONS_JOB'))
);

-- changeset lee.kitching:1757938355304-2 splitStatements:false
CREATE TABLE IF NOT EXISTS "offender" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "checkin_interval" INTERVAL SECOND(6) NOT NULL,
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "date_of_birth" date,
    "email" VARCHAR(255) CONSTRAINT "uk2skscndsnwbyn2p41fbt2nolv" UNIQUE,
    "first_checkin" date,
    "first_name" VARCHAR(255) NOT NULL,
    "last_name" VARCHAR(255) NOT NULL,
    "phone_number" VARCHAR(255) CONSTRAINT "uk3cixhi6bhep1th15swcwg7imb" UNIQUE,
    "practitioner" VARCHAR(255) NOT NULL,
    "status" VARCHAR(255) NOT NULL,
    "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "uuid" UUID NOT NULL CONSTRAINT "uknke7wygy3ii1ov996d6b88n4" UNIQUE,
    "crn" VARCHAR(255),
    CONSTRAINT "offender_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "offender_status_check" CHECK (status IN ('INITIAL', 'VERIFIED', 'INACTIVE'))
);

-- changeset lee.kitching:1757938355304-3 splitStatements:false
CREATE TABLE IF NOT EXISTS "offender_checkin" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_check_auto" VARCHAR(255),
    "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "due_date" date,
    "id_check_manual" VARCHAR(255),
    "reviewed_at" TIMESTAMP(6) WITH TIME ZONE,
    "reviewed_by" VARCHAR(255),
    "status" VARCHAR(255) NOT NULL,
    "submitted_at" TIMESTAMP(6) WITH TIME ZONE,
    "survey_response" JSONB,
    "uuid" UUID NOT NULL,
    "offender_id" BIGINT NOT NULL,
    CONSTRAINT "offender_checkin_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fkaw1ldx7ysswxfgiukxn22mgkw" FOREIGN KEY ("offender_id") REFERENCES "offender" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "uklth9ca62c9i7tsyc591i2wqac" UNIQUE(uuid),
    CONSTRAINT "offender_checkin_id_check_auto_check" CHECK (id_check_auto IN ('MATCH', 'NO_MATCH')),
    CONSTRAINT "offender_checkin_id_check_manual_check" CHECK (id_check_manual IN ('MATCH', 'NO_MATCH')),
    CONSTRAINT "offender_checkin_status_check" CHECK (status IN ('CREATED', 'SUBMITTED', 'REVIEWED', 'CANCELLED', 'EXPIRED'))
);

-- changeset lee.kitching:1757938355304-4 splitStatements:false
CREATE TABLE IF NOT EXISTS "offender_checkin_notification" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "checkin" UUID NOT NULL,
    "created_at" TIMESTAMP(6) WITH TIME ZONE,
    "notification_id" UUID NOT NULL,
    "reference" VARCHAR(255) NOT NULL,
    "status" VARCHAR(255),
    "updated_at" TIMESTAMP(6) WITH TIME ZONE,
    "job_log" BIGINT,
    CONSTRAINT "offender_checkin_notification_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk1x2mh4x4wsuchrgjifsmu3xce" FOREIGN KEY ("job_log") REFERENCES "job_log" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "idx_checkin_notification_notification_id" UNIQUE(notification_id)
);

-- changeset lee.kitching:1757938355304-5 splitStatements:false
CREATE TABLE IF NOT EXISTS "offender_event_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "comment" VARCHAR(255),
    "created_at" TIMESTAMP(6) WITH TIME ZONE,
    "log_entry_type" VARCHAR(255) NOT NULL,
    "practitioner" VARCHAR(255),
    "uuid" UUID NOT NULL,
    "checkin" BIGINT,
    "offender_id" BIGINT,
    CONSTRAINT "offender_event_log_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk2pd7cm10eqhlua9jmoe0nvc64" FOREIGN KEY ("offender_id") REFERENCES "offender" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fkb4jr1vons6qh483fjcnketil7" FOREIGN KEY ("checkin") REFERENCES "offender_checkin" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "uk34rf0tar5xcgtu3443uxw8p0f" UNIQUE(uuid),
    CONSTRAINT "offender_event_log_log_entry_type_check" CHECK (log_entry_type IN ('OFFENDER_DEACTIVATED', 'OFFENDER_CHECKIN_NOT_SUBMITTED'))
);

-- changeset lee.kitching:1757938355304-6 splitStatements:false
CREATE TABLE IF NOT EXISTS "offender_setup" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP(6) WITH TIME ZONE,
    "practitioner" VARCHAR(255) NOT NULL,
    "uuid" UUID NOT NULL,
    "offender_id" BIGINT,
    CONSTRAINT "offender_setup_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fkomtdpq2kq9dhwa0v72p03yue5" FOREIGN KEY ("offender_id") REFERENCES "offender" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "ukspt62ukihi9jw682b0skkbplp" UNIQUE(uuid)
);

-- changeset lee.kitching:1757938355304-7 splitStatements:false
CREATE INDEX IF NOT EXISTS "idx_job_log_job_type" ON "job_log" USING btree("job_type");

-- changeset lee.kitching:1757938355304-8 splitStatements:false
CREATE INDEX IF NOT EXISTS "idx_job_log_created_at" ON "job_log" USING btree("created_at");

-- changeset lee.kitching:1757938355304-9 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_status_idx" ON "offender" USING btree("status");

-- changeset lee.kitching:1757938355304-10 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_created_at_idx" ON "offender" USING btree("created_at");

-- changeset lee.kitching:1757938355304-11 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_practitioner" ON "offender" USING btree("practitioner");

-- changeset lee.kitching:1757938355304-12 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_crn_idx" ON "offender" USING btree("crn");

-- changeset lee.kitching:1757938355304-13 splitStatements:false
CREATE INDEX IF NOT EXISTS "checkin_due_date_idx" ON "offender_checkin" USING btree("due_date");

-- changeset lee.kitching:1757938355304-14 splitStatements:false
CREATE INDEX IF NOT EXISTS "checkin_created_at_idx" ON "offender_checkin" USING btree("created_at");

-- changeset lee.kitching:1757938355304-15 splitStatements:false
CREATE INDEX IF NOT EXISTS "checkin_status_idx" ON "offender_checkin" USING btree("status");

-- changeset lee.kitching:1757938355304-16 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_checkin_offender_idx" ON "offender_checkin" USING btree("offender_id");

-- changeset lee.kitching:1757938355304-17 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_checkin_created_by_idx" ON "offender_checkin" USING btree("created_by");

-- changeset lee.kitching:1757938355304-18 splitStatements:false
CREATE INDEX IF NOT EXISTS "idx_checkin_notification_reference" ON "offender_checkin_notification" USING btree("reference");

-- changeset lee.kitching:1757938355304-19 splitStatements:false
CREATE INDEX IF NOT EXISTS "idx_chckin_notification_created_at" ON "offender_checkin_notification" USING btree("created_at");

-- changeset lee.kitching:1757938355304-20 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_event_log_log_entry_type_idx" ON "offender_event_log" USING btree("log_entry_type");

-- changeset lee.kitching:1757938355304-21 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_event_log_offender_idx" ON "offender_event_log" USING btree("offender_id");

-- changeset lee.kitching:1757938355304-22 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_event_log_practitioner_idx" ON "offender_event_log" USING btree("practitioner");

-- changeset lee.kitching:1757938355304-23 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_setup_created_at_idx" ON "offender_setup" USING btree("created_at");

-- changeset lee.kitching:1757938355304-24 splitStatements:false
CREATE INDEX IF NOT EXISTS "offender_setup_practitioner_idx" ON "offender_setup" USING btree("practitioner");

-- changeset lee.kitching:1757938355304-25 splitStatements:false
CREATE TABLE IF NOT EXISTS "shedlock" (
    "name" VARCHAR(64) NOT NULL,
    "lock_until" TIMESTAMP(6) WITH TIME ZONE,
    "locked_at" TIMESTAMP(6) WITH TIME ZONE,
    "locked_by" VARCHAR(255),
    CONSTRAINT "shedlock_pkey" PRIMARY KEY ("name")
);
